version: '3'
services:
  monerod:
    image: ghcr.io/sethforprivacy/simple-monerod:latest
    restart: unless-stopped
    container_name: monerod
    volumes:
      - xmrdata:/home/pool/monero/.bitmonero
    ports:
      - 18080:18080
      - 18089:18089
    depends_on:
        - explore
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=18089"
      - "--public-node"
      - "--no-igd"
      - "--enable-dns-blocklist"

  explore:
    image: xmrblocks:latest
    build: ./inion-xmr-explorer
    container_name: explore
    restart: unless-stopped
    volumes:
      - xmrdata:/home/pool/monero/.bitmonero
    ports:
      - 8081:8081
    command: ["./xmrblocks --daemon-url=monerod:18089 --enable-json-api --enable-autorefresh-option --enable-emission-monitor --enable-pusher"]

volumes:
  xmrdata:
